import { HtBounds, HtMap, HtMapType, MapUtils } from "./interfaces";
export declare class HtMapItem {
    mapType: HtMapType;
    item: any;
    data: any;
    isFaded: boolean;
    isHighlighted: boolean;
    isOld: boolean;
    id: string | number;
    defaultStyle: any;
    googleStyle: {};
    leafletStyle: {};
    mapUtils: MapUtils;
    defaultOptions: {
        mapType: string;
        defaultStyle: {};
    };
    constructor(mapType: HtMapType, options?: {});
    setItem(): void;
    setMapTypeStyle(): void;
    update(item: any, map: HtMap): void;
    onUpdate(item: any, map: any): void;
    updateItem(data: any): void;
    extendBounds(bounds: HtBounds): HtBounds;
    setMap(map: any): void;
    clear(): void;
    resetHighlight(map: any): void;
    reset(): void;
    resetItem(): void;
    setStyle(style: any): void;
    getItemInfoContent(): string;
    getInfoContent(item: any): string;
    openPopup(item: any, content?: string): void;
    closePopup(): void;
    openTooltip(content?: string): void;
    closeTooltip(): void;
    bringToFront(): void;
    highlight(map: HtMap): void;
    unHighlight(map: HtMap): void;
    setFocus(map: any): void;
}
